### ISSUE TITLE
Registration :: Feature request

### ISSUE THREAD

**Issue by ghost** [Sebazzz/IFS#37]
Hi @Sebazzz,

Do you have any plans on adding registration functionality where a user can register an account and on register an directory would be created for them folder name `<username>` this would also be cool set quotas per user. This directory would be there storage block.

**Comment by Sebazzz** [comment]
Plans, no, but I did just implement SSO using OpenID Connect so at least it is possible to distinguish users.

What would be the point to namespacing the uploads per users? Can you expand on your use case?

**Comment by ghost** [comment]
Hi @Sebazzz,

I think it would be good idea to separate users data within separate directories making it easier to archive there data, but I do not think you will make use of such feature where admin can `tar` the entire user directory and back it up for the customer.

**Comment by Sebazzz** [comment]
Ah, right. Yes, but by default the uploads expire so an archive is of limited use.

**Comment by ghost** [comment]
I see,  I will close this issue now.
